bot:
  token: 8554086488:AAGoOfE3eBuoM7O-S-ItzgHru7iYUsLFO2k
  username: helper_vvbot

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/support_bot_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  application:
    name: support-bot

client:
  name: CLIENT

support:
  name: SUPPORT

# JWT Configuration
jwt:
  secret: MyVerySecureSecretKeyForJWTTokenGenerationAndValidation2024SupportBot
  expiration: 86400000  # 24 soat (milliseconds)

# File upload configuration
file:
  upload-dir: uploads
  max-size: 10MB